// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkciXXgwwSo-o-WVD-GrVIFIJAFrcgYwc',
    appId: '1:1087977237588:web:aa3ee75d8216fb0e27d1c1',
    messagingSenderId: '1087977237588',
    projectId: 'sambaternak-firebase',
    authDomain: 'sambaternak-firebase.firebaseapp.com',
    storageBucket: 'sambaternak-firebase.appspot.com',
    measurementId: 'G-BE53QH2J2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdjoZBTmQmG_qDpBKdq3QWCXrpr8UyjkQ',
    appId: '1:1087977237588:android:daf85d9161d0d92927d1c1',
    messagingSenderId: '1087977237588',
    projectId: 'sambaternak-firebase',
    storageBucket: 'sambaternak-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIC5Z_4dcRYWDjCLahppRGzLE0E89QJKA',
    appId: '1:1087977237588:ios:c5c99c722c7d69c427d1c1',
    messagingSenderId: '1087977237588',
    projectId: 'sambaternak-firebase',
    storageBucket: 'sambaternak-firebase.appspot.com',
    iosClientId: '1087977237588-2oeplutm5js5u2a8adshag9a605vh3ir.apps.googleusercontent.com',
    iosBundleId: 'com.example.sambaternakFlutterFbs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIC5Z_4dcRYWDjCLahppRGzLE0E89QJKA',
    appId: '1:1087977237588:ios:c5c99c722c7d69c427d1c1',
    messagingSenderId: '1087977237588',
    projectId: 'sambaternak-firebase',
    storageBucket: 'sambaternak-firebase.appspot.com',
    iosClientId: '1087977237588-2oeplutm5js5u2a8adshag9a605vh3ir.apps.googleusercontent.com',
    iosBundleId: 'com.example.sambaternakFlutterFbs',
  );
}
